language: ruby
rvm:
  - 2.2.5 --with-gcc=clang
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_install:
  - gem update --system
  - gem install bundler
  - gem install --pre rails -v 5.1.0.beta1
before_script:
  - psql -c 'create database Overtime_test;' -U postgres
notifications:
  slack: railsdevkev:2Hc03EHDhMxN6F9bDx4pm3dJ